#nanodisco config file

strain:
    - SC11A_H2
#    - SC11A_H5
#    - SC11A_H8
#    - SC12A_B2
#    - SC12A_E1
#    - SC12A_F6
#    - SC12A_H6


sample:
#H2
    - H2_1_M9
    - H2_2_M9
#    - H2_1_LB
    - H2_1_96
#    - H2_1_25
#    - H2_1_42

#H5
#    - H5_1_M9
#    - H5_2_M9
#    - H5_1_LB
#    - H5_1_96
#    - H5_1_25
#    - H5_1_42


#H8
#    - H8_1_M9
#    - H8_2_M9
#    - H8_1_LB
#    - H8_1_96
#    - H8_1_25
#    - H8_1_42

#B2
#    - B2_1_M9
#    - B2_2_M9
#    - B2_1_LB
#    - B2_1_96
#    - B2_1_25
#    - B2_1_42

#E1
#    - E1_1_M9
#    - E1_2_M9
#    - E1_1_LB
#    - E1_1_96
#    - E1_1_25
#    - E1_1_42

#F6
#    - F6_1_M9
#    - F6_2_M9
#    - F6_1_LB
#    - F6_1_96
#    - F6_1_25
#    - F6_1_42

#H6
#    - H6_1_M9
#    - H6_2_M9
#    - H6_1_LB
#    - H6_1_96
#    - H6_1_25
#    - H6_1_42